import type {
  Customer,
  Contact,
  Product,
  Deal,
  CrmReminder,
  DealActivity,
  DealTask,
} from "./types";

export const products: Product[] = [
  {
    id: "prod-1",
    sku: "KRN-BLDC-AC-01",
    model: "Kryon AC Pro 1200",
    motorControllerType: "BLDC Indoor",
    voltage: 230,
    wattage: 1200,
    poles: 4,
    sensorType: "Hall Sensor (3-wire)",
    hsnCode: "85044090",
    sellingPrice: 1850,
    description:
      "High-efficiency BLDC controller for 1.5T split AC indoor units with hall commutation.",
    specSheet: { id: "spec-1", name: "kryon-ac-pro-1200-spec.pdf" },
  },
  {
    id: "prod-2",
    sku: "KRN-BLDC-CF-02",
    model: "Kryon FanDrive 75",
    motorControllerType: "BLDC Indoor",
    voltage: 230,
    wattage: 75,
    poles: 4,
    sensorType: "Sensorless (Back-EMF)",
    hsnCode: "85044090",
    sellingPrice: 420,
    description: "Sensorless BLDC driver for ceiling fan applications.",
  },
  {
    id: "prod-3",
    sku: "KRN-BLDC-EF-03",
    model: "Kryon Exhaust 40",
    motorControllerType: "BLDC Indoor",
    voltage: 230,
    wattage: 40,
    poles: 2,
    sensorType: "Sensorless (Back-EMF)",
    hsnCode: "85044090",
    sellingPrice: 310,
    description: "Compact controller for exhaust and ventilation fans.",
  },
  {
    id: "prod-4",
    sku: "KRN-BLDC-WP-04",
    model: "Kryon AquaDrive 60",
    motorControllerType: "BLDC Indoor",
    voltage: 24,
    wattage: 60,
    poles: 4,
    sensorType: "Hall Sensor (3-wire)",
    hsnCode: "85044090",
    sellingPrice: 680,
    description: "24V BLDC controller for water purifier pump motors.",
    specSheet: { id: "spec-4", name: "kryon-aquadrive-60-drawing.pdf" },
  },
  {
    id: "prod-5",
    sku: "KRN-PMSM-RF-05",
    model: "Kryon CoolSync 150",
    motorControllerType: "PMSM",
    voltage: 230,
    wattage: 150,
    poles: 6,
    sensorType: "Resolver",
    hsnCode: "85044090",
    sellingPrice: 2200,
    description: "PMSM compressor controller for inverter refrigerator platforms.",
  },
  {
    id: "prod-6",
    sku: "KRN-BLDC-WM-06",
    model: "Kryon WashDrive 500",
    motorControllerType: "BLDC Outdoor",
    voltage: 230,
    wattage: 500,
    poles: 4,
    sensorType: "Hall Sensor (3-wire)",
    hsnCode: "85044090",
    sellingPrice: 1450,
    description: "Outdoor-rated BLDC controller for direct-drive washing machines.",
  },
];

export const customers: Customer[] = [
  {
    id: "cust-1",
    name: "Voltas Beko",
    oemSegment: "Room AC",
    leadSource: "Trade Expo",
    leadDate: "2025-02-14",
    plantLocations: ["Pantnagar, Uttarakhand", "Sanand, Gujarat"],
    productionCapacity: "2500000",
    annualRevenueRange: "> 5000 Cr",
    gstin: "05AABCV1234F1Z5",
    websiteUrl: "https://www.voltasbeko.com",
    registeredOfficeAddress: "Voltas House, Dr. Babasaheb Ambedkar Road, Mumbai 400025",
    factoryAddress: "Plot 12, SIDCO Industrial Estate, Pantnagar, Uttarakhand",
    vendorStatus: "Approved",
    registrationFormSubmittedDate: "2025-03-01",
    expectedApprovalDate: "2025-04-15",
    vendorCode: "VND-VB-001",
    registrationDocuments: [
      { id: "doc-1", name: "vendor-registration-voltas.pdf" },
      { id: "doc-2", name: "gst-certificate.pdf" },
    ],
    registrationRemarks: "Approved after quality audit at Pantnagar plant.",
    priority: "A",
    accountOwner: "Rajesh Kumar",
    tier: "Tier 1",
    estimatedAnnualPotential: "125000000",
    notes:
      "Key strategic account. Exploring BLDC migration across full AC range by FY27.",
    customerProducts: [
      {
        id: "cprod-1",
        productSkuOrModel: "INV-AC-1.5T-STD",
        annualQuantityPcs: 850000,
        currentPurchasePrice: 1620,
        voltage: 230,
        wattage: 1100,
        poles: 4,
        primarySupplier: {
          name: "Nidec India",
          volume: "600k pcs/yr",
          purchasePrice: 1620,
        },
        secondarySupplier: {
          name: "Bharat Electronics Motors",
          volume: "250k pcs/yr",
          purchasePrice: 1680,
        },
      },
      {
        id: "cprod-2",
        productSkuOrModel: "INV-AC-2T-PREM",
        annualQuantityPcs: 320000,
        monthlyOfftakePcs: 28000,
        currentPurchasePrice: 1980,
        voltage: 230,
        wattage: 1400,
        poles: 4,
        primarySupplier: {
          name: "Nidec India",
          volume: "320k pcs/yr",
          purchasePrice: 1980,
        },
      },
    ],
  },
  {
    id: "cust-2",
    name: "Havells India",
    oemSegment: "Ceiling Fan",
    leadSource: "Website Inquiry",
    leadDate: "2025-01-08",
    plantLocations: ["Alwar, Rajasthan", "Baddi, Himachal Pradesh"],
    productionCapacity: "8000000",
    annualRevenueRange: "> 5000 Cr",
    gstin: "08AABCH5678G1Z3",
    websiteUrl: "https://www.havells.com",
    registeredOfficeAddress: "904, Surya Kiran Building, Kasturba Gandhi Marg, New Delhi 110001",
    factoryAddress: "Alwar Manufacturing Complex, RIICO Industrial Area, Alwar, Rajasthan",
    vendorStatus: "Approved",
    registrationFormSubmittedDate: "2025-01-20",
    expectedApprovalDate: "2025-03-10",
    vendorCode: "VND-HV-014",
    registrationDocuments: [{ id: "doc-3", name: "havells-vendor-pack.pdf" }],
    registrationRemarks: "Fast-tracked after reference from existing BLDC program.",
    priority: "A",
    accountOwner: "Priya Sharma",
    tier: "Tier 1",
    estimatedAnnualPotential: "98000000",
    notes:
      "Strong relationship with procurement head. Evaluating sensorless BLDC for economy range.",
    customerProducts: [
      {
        id: "cprod-3",
        productSkuOrModel: "CF-ECO-1200MM",
        annualQuantityPcs: 2400000,
        currentPurchasePrice: 385,
        voltage: 230,
        wattage: 70,
        poles: 4,
        primarySupplier: {
          name: "Crompton Greaves Motors",
          volume: "1.8M pcs/yr",
          purchasePrice: 385,
        },
        secondarySupplier: {
          name: "Orient Electric Components",
          volume: "600k pcs/yr",
          purchasePrice: 392,
        },
      },
    ],
  },
  {
    id: "cust-3",
    name: "Crompton Greaves",
    oemSegment: "Exhaust Fan",
    leadSource: "Referral",
    leadDate: "2025-04-02",
    plantLocations: ["Ahmedabad, Gujarat"],
    productionCapacity: "3000000",
    annualRevenueRange: "1000-5000 Cr",
    gstin: "24AABCC9012H1Z7",
    websiteUrl: "https://www.crompton.co.in",
    registeredOfficeAddress: "Crompton Greaves House, Kanjurmarg East, Mumbai 400042",
    factoryAddress: "GIDC Estate, Vatva, Ahmedabad, Gujarat",
    vendorStatus: "In Process",
    registrationFormSubmittedDate: "2025-05-12",
    expectedApprovalDate: "2025-07-01",
    vendorCode: "",
    registrationDocuments: [{ id: "doc-4", name: "crompton-registration-draft.pdf" }],
    registrationRemarks: "Awaiting finance clearance on payment terms.",
    priority: "B",
    accountOwner: "Amit Patel",
    tier: "Tier 2",
    estimatedAnnualPotential: "42000000",
    notes: "Vendor registration in progress. Price-sensitive buyer.",
    customerProducts: [],
  },
  {
    id: "cust-4",
    name: "Bajaj Electricals",
    oemSegment: "Water Purifier",
    leadSource: "Cold Outreach",
    leadDate: "2024-11-18",
    plantLocations: ["Chakan, Maharashtra", "Wardha, Maharashtra"],
    productionCapacity: "1200000",
    annualRevenueRange: "1000-5000 Cr",
    gstin: "27AABCB3456I1Z9",
    websiteUrl: "https://www.bajajelectricals.com",
    registeredOfficeAddress: "Bajaj Bhavan, Mumbai-Pune Road, Akurdi, Pune 411035",
    factoryAddress: "Chakan MIDC, Pune, Maharashtra",
    vendorStatus: "Approved",
    registrationFormSubmittedDate: "2024-12-05",
    expectedApprovalDate: "2025-01-20",
    vendorCode: "VND-BJ-022",
    registrationDocuments: [{ id: "doc-5", name: "bajaj-vendor-approval.pdf" }],
    registrationRemarks: "Approved for 24V pump controller category.",
    priority: "B",
    accountOwner: "Sneha Reddy",
    tier: "Tier 2",
    estimatedAnnualPotential: "36000000",
    notes: "Interested in 24V BLDC for new purifier platform launch Q3 2026.",
    customerProducts: [],
  },
  {
    id: "cust-5",
    name: "Whirlpool India",
    oemSegment: "Refrigerator",
    leadSource: "Industry Event",
    leadDate: "2025-03-22",
    plantLocations: ["Faridabad, Haryana", "Pune, Maharashtra"],
    productionCapacity: "4000000",
    annualRevenueRange: "1000-5000 Cr",
    gstin: "06AABCW7890J1Z1",
    websiteUrl: "https://www.whirlpoolindia.com",
    registeredOfficeAddress: "Whirlpool House, Plot 40, Sector 44, Gurugram 122002",
    factoryAddress: "Industrial Area, Faridabad, Haryana",
    vendorStatus: "Approved",
    registrationFormSubmittedDate: "2025-04-10",
    expectedApprovalDate: "2025-06-01",
    vendorCode: "VND-WP-008",
    registrationDocuments: [{ id: "doc-6", name: "whirlpool-vendor-form.pdf" }],
    registrationRemarks: "Compressor controller category approved.",
    priority: "A",
    accountOwner: "Rajesh Kumar",
    tier: "Tier 1",
    estimatedAnnualPotential: "87000000",
    notes:
      "PMSM compressor controller evaluation for inverter refrigerator line.",
    customerProducts: [],
  },
  {
    id: "cust-6",
    name: "V-Guard Industries",
    oemSegment: "Washing Machine",
    leadSource: "LinkedIn",
    leadDate: "2025-05-28",
    plantLocations: ["Coimbatore, Tamil Nadu"],
    productionCapacity: "600000",
    annualRevenueRange: "1000-5000 Cr",
    gstin: "33AABCV2345K1Z4",
    websiteUrl: "https://www.vguard.in",
    registeredOfficeAddress: "42/962, Vennala High School Road, Vennala, Kochi 682028",
    factoryAddress: "SIDCO Industrial Estate, Coimbatore, Tamil Nadu",
    vendorStatus: "Not Started",
    registrationFormSubmittedDate: "",
    expectedApprovalDate: "",
    vendorCode: "",
    registrationDocuments: [],
    registrationRemarks: "",
    priority: "C",
    accountOwner: "Amit Patel",
    tier: "Tier 3",
    estimatedAnnualPotential: "18000000",
    notes:
      "Early-stage discussion. Exploring direct-drive BLDC for premium WM range.",
    customerProducts: [],
  },
];

export const contacts: Contact[] = [
  {
    id: "cont-1",
    customerId: "cust-1",
    name: "Vikram Mehta",
    designation: "VP — Sourcing",
    department: "Purchase",
    phone: "+91 98765 43210",
    email: "vikram.mehta@voltasbeko.com",
    officePhone: "+91 22 6123 4500",
    buyingRole: "Decision Maker",
    reportsTo: "Anita Desai",
    isPrimary: true,
    linkedInUrl: "https://linkedin.com/in/vikram-mehta",
    birthdayOrAnniversary: "1982-03-15",
    notes: "Prefers WhatsApp for quick updates. Final sign-off on annual POs.",
  },
  {
    id: "cont-2",
    customerId: "cust-1",
    name: "Anita Desai",
    designation: "Sr. Manager — R&D",
    department: "R&D",
    phone: "+91 98765 43211",
    email: "anita.desai@voltasbeko.com",
    buyingRole: "Influencer",
    reportsTo: "Vikram Mehta",
    isPrimary: false,
    notes: "Technical evaluator for motor specs and validation reports.",
  },
  {
    id: "cont-3",
    customerId: "cust-2",
    name: "Rohit Jain",
    designation: "Head — Electrical",
    department: "R&D",
    phone: "+91 98123 45678",
    email: "rohit.jain@havells.com",
    officePhone: "+91 124 456 7800",
    buyingRole: "Decision Maker",
    isPrimary: true,
    linkedInUrl: "https://linkedin.com/in/rohit-jain-havells",
  },
  {
    id: "cont-4",
    customerId: "cust-2",
    name: "Kavita Nair",
    designation: "Purchase Manager",
    department: "Purchase",
    phone: "+91 98123 45679",
    email: "kavita.nair@havells.com",
    buyingRole: "Gatekeeper",
    reportsTo: "Rohit Jain",
    isPrimary: false,
  },
  {
    id: "cont-5",
    customerId: "cust-3",
    name: "Suresh Iyer",
    designation: "GM — Operations",
    department: "Operations",
    phone: "+91 98234 56789",
    email: "suresh.iyer@crompton.com",
    buyingRole: "Decision Maker",
    isPrimary: true,
  },
  {
    id: "cont-6",
    customerId: "cust-4",
    name: "Meera Joshi",
    designation: "Product Manager",
    department: "R&D",
    phone: "+91 98345 67890",
    email: "meera.joshi@bajajelectricals.com",
    buyingRole: "Champion",
    isPrimary: true,
    notes: "Internal advocate pushing BLDC upgrade for premium range.",
  },
  {
    id: "cont-7",
    customerId: "cust-5",
    name: "Arun Khanna",
    designation: "Director — Engineering",
    department: "Management",
    phone: "+91 98456 78901",
    email: "arun.khanna@whirlpool.com",
    officePhone: "+91 124 456 7890",
    buyingRole: "Decision Maker",
    isPrimary: true,
    birthdayOrAnniversary: "1975-11-08",
  },
  {
    id: "cont-8",
    customerId: "cust-5",
    name: "Deepa Menon",
    designation: "Sr. Engineer — Motors",
    department: "R&D",
    phone: "+91 98456 78902",
    email: "deepa.menon@whirlpool.com",
    buyingRole: "Influencer",
    reportsTo: "Arun Khanna",
    isPrimary: false,
  },
  {
    id: "cont-9",
    customerId: "cust-6",
    name: "Ganesh Subramanian",
    designation: "Head — Sourcing",
    department: "Vendor Development",
    phone: "+91 98567 89012",
    email: "ganesh.s@v-guard.in",
    buyingRole: "Decision Maker",
    isPrimary: true,
  },
];

export const deals: Deal[] = [
  {
    id: "DEAL-2026-001",
    customerId: "cust-1",
    contactId: "cont-1",
    productId: "prod-1",
    quantity: 250000,
    estimatedAnnualValue: 462500000,
    currentSupplierPrice: 2100,
    quotedPrice: 1850,
    confidence: 75,
    stage: "Commercial Negotiation",
    stageEnteredAt: "2026-05-15",
    lastActivityAt: "2026-05-28",
    owner: "Rajesh Kumar",
  },
  {
    id: "DEAL-2026-002",
    customerId: "cust-2",
    contactId: "cont-3",
    productId: "prod-2",
    quantity: 180000,
    estimatedAnnualValue: 75600000,
    currentSupplierPrice: 480,
    quotedPrice: 420,
    confidence: 100,
    stage: "PO Received",
    stageEnteredAt: "2026-06-01",
    lastActivityAt: "2026-06-08",
    owner: "Priya Sharma",
  },
  {
    id: "DEAL-2026-003",
    customerId: "cust-3",
    contactId: "cont-5",
    productId: "prod-3",
    quantity: 120000,
    estimatedAnnualValue: 37200000,
    currentSupplierPrice: 350,
    quotedPrice: 310,
    confidence: 50,
    stage: "Discussion",
    stageEnteredAt: "2026-04-20",
    lastActivityAt: "2026-05-20",
    owner: "Amit Patel",
  },
  {
    id: "DEAL-2026-004",
    customerId: "cust-4",
    contactId: "cont-6",
    productId: "prod-4",
    quantity: 80000,
    estimatedAnnualValue: 54400000,
    currentSupplierPrice: 750,
    quotedPrice: 680,
    confidence: 75,
    stage: "PFI Sent",
    stageEnteredAt: "2026-05-22",
    lastActivityAt: "2026-06-05",
    owner: "Sneha Reddy",
  },
  {
    id: "DEAL-2026-005",
    customerId: "cust-5",
    contactId: "cont-7",
    productId: "prod-5",
    quantity: 150000,
    estimatedAnnualValue: 330000000,
    currentSupplierPrice: 2500,
    quotedPrice: 2200,
    confidence: 50,
    stage: "Commercial Negotiation",
    stageEnteredAt: "2026-05-01",
    lastActivityAt: "2026-05-18",
    owner: "Rajesh Kumar",
  },
  {
    id: "DEAL-2026-006",
    customerId: "cust-6",
    contactId: "cont-9",
    productId: "prod-6",
    quantity: 45000,
    estimatedAnnualValue: 65250000,
    currentSupplierPrice: 1650,
    quotedPrice: 1450,
    confidence: 25,
    stage: "Discussion",
    stageEnteredAt: "2026-03-10",
    lastActivityAt: "2026-03-25",
    owner: "Amit Patel",
  },
  {
    id: "DEAL-2026-007",
    customerId: "cust-1",
    contactId: "cont-2",
    productId: "prod-1",
    quantity: 50000,
    estimatedAnnualValue: 92500000,
    currentSupplierPrice: 2100,
    quotedPrice: 1850,
    confidence: 25,
    stage: "Lead - Hot",
    stageEnteredAt: "2026-06-05",
    lastActivityAt: "2026-06-08",
    owner: "Rajesh Kumar",
  },
  {
    id: "DEAL-2026-008",
    customerId: "cust-2",
    contactId: "cont-4",
    productId: "prod-2",
    quantity: 100000,
    estimatedAnnualValue: 42000000,
    currentSupplierPrice: 480,
    quotedPrice: 420,
    confidence: 50,
    stage: "Lead - Hot",
    stageEnteredAt: "2026-05-10",
    lastActivityAt: "2026-05-25",
    owner: "Priya Sharma",
  },
  {
    id: "DEAL-2026-009",
    customerId: "cust-3",
    contactId: "cont-5",
    productId: "prod-3",
    quantity: 30000,
    estimatedAnnualValue: 9300000,
    currentSupplierPrice: 350,
    quotedPrice: 310,
    confidence: 0,
    stage: "Closed Lost",
    stageEnteredAt: "2026-02-15",
    lastActivityAt: "2026-04-01",
    owner: "Amit Patel",
  },
  {
    id: "DEAL-2026-010",
    customerId: "cust-5",
    contactId: "cont-8",
    productId: "prod-5",
    quantity: 200000,
    estimatedAnnualValue: 440000000,
    currentSupplierPrice: 2500,
    quotedPrice: 2200,
    confidence: 100,
    stage: "Closed Won",
    stageEnteredAt: "2026-04-10",
    lastActivityAt: "2026-05-30",
    owner: "Rajesh Kumar",
  },
  {
    id: "DEAL-2026-011",
    customerId: "cust-4",
    contactId: "cont-6",
    productId: "prod-4",
    quantity: 10000,
    estimatedAnnualValue: 6800000,
    currentSupplierPrice: 750,
    quotedPrice: 680,
    confidence: 25,
    stage: "Lead - Hot",
    stageEnteredAt: "2026-01-15",
    lastActivityAt: "2026-02-01",
    owner: "Sneha Reddy",
  },
];

export const dealTasks: DealTask[] = [
  {
    id: "task-1",
    dealId: "DEAL-2026-001",
    title: "Present revised pricing with volume discount tiers",
    dueDate: "2026-06-14",
    status: "in_progress",
    createdAt: "2026-05-28T10:00:00.000Z",
    createdByUserId: "user-admin",
    assignedToUserId: "user-2",
  },
  {
    id: "task-2",
    dealId: "DEAL-2026-002",
    title: "Kick-off production planning meeting",
    dueDate: "2026-06-16",
    status: "pending",
    createdAt: "2026-06-08T10:00:00.000Z",
    createdByUserId: "user-2",
    assignedToUserId: "user-2",
  },
  {
    id: "task-3",
    dealId: "DEAL-2026-003",
    title: "Follow up on lab test results — no response in 3 weeks",
    dueDate: "2026-06-10",
    status: "in_progress",
    createdAt: "2026-05-20T10:00:00.000Z",
    createdByUserId: "user-3",
    assignedToUserId: "user-3",
  },
  {
    id: "task-4",
    dealId: "DEAL-2026-004",
    title: "Schedule PFI review call with procurement",
    dueDate: "2026-06-13",
    status: "pending",
    createdAt: "2026-06-05T10:00:00.000Z",
    createdByUserId: "user-4",
    assignedToUserId: "user-4",
  },
  {
    id: "task-5",
    dealId: "DEAL-2026-005",
    title: "Chase sample evaluation status — overdue",
    dueDate: "2026-06-11",
    status: "in_progress",
    createdAt: "2026-05-18T10:00:00.000Z",
    createdByUserId: "user-admin",
    assignedToUserId: "user-admin",
  },
  {
    id: "task-6",
    dealId: "DEAL-2026-006",
    title: "Re-engage after initial technical presentation",
    dueDate: "2026-06-12",
    status: "pending",
    createdAt: "2026-03-25T10:00:00.000Z",
    createdByUserId: "user-3",
    assignedToUserId: "user-3",
  },
  {
    id: "task-7",
    dealId: "DEAL-2026-007",
    title: "Send product datasheet for 1.5T variant",
    dueDate: "2026-06-15",
    status: "pending",
    createdAt: "2026-06-08T10:00:00.000Z",
    createdByUserId: "user-admin",
    assignedToUserId: "user-admin",
  },
  {
    id: "task-8",
    dealId: "DEAL-2026-008",
    title: "Follow up on technical specs for economy fan range",
    dueDate: "2026-06-14",
    status: "pending",
    createdAt: "2026-05-25T10:00:00.000Z",
    createdByUserId: "user-2",
    assignedToUserId: "user-2",
  },
  {
    id: "task-9",
    dealId: "DEAL-2026-009",
    title: "Archive — lost to competitor on price",
    dueDate: "2026-04-01",
    status: "completed",
    completedAt: "2026-04-01",
    createdAt: "2026-02-15T10:00:00.000Z",
    createdByUserId: "user-3",
    assignedToUserId: "user-3",
  },
  {
    id: "task-10",
    dealId: "DEAL-2026-010",
    title: "Annual review meeting scheduled",
    dueDate: "2026-07-01",
    status: "pending",
    createdAt: "2026-05-30T10:00:00.000Z",
    createdByUserId: "user-admin",
    assignedToUserId: "user-admin",
  },
  {
    id: "task-11",
    dealId: "DEAL-2026-011",
    title: "Send re-engagement email with new case study",
    dueDate: "2026-06-16",
    status: "pending",
    createdAt: "2026-02-01T10:00:00.000Z",
    createdByUserId: "user-4",
    assignedToUserId: "user-4",
  },
];

export const dealActivities: DealActivity[] = [
  {
    id: "activity-1",
    dealId: "DEAL-2026-001",
    type: "call",
    occurredAt: "2026-05-28",
    contactId: "cont-1",
    summary: "Discussed volume tiers and competitor pricing with procurement.",
    outcome: "Requested revised quote by mid-June.",
    loggedByUserId: "user-admin",
    createdAt: "2026-05-28T14:30:00.000Z",
  },
  {
    id: "activity-2",
    dealId: "DEAL-2026-003",
    type: "email",
    occurredAt: "2026-05-20",
    contactId: "cont-5",
    summary: "Sent follow-up on lab test results.",
    loggedByUserId: "user-3",
    createdAt: "2026-05-20T11:00:00.000Z",
  },
  {
    id: "activity-3",
    dealId: "DEAL-2026-004",
    type: "meeting",
    occurredAt: "2026-06-05",
    contactId: "cont-6",
    summary: "PFI walkthrough with procurement and engineering.",
    outcome: "PFI sent; review call to be scheduled.",
    loggedByUserId: "user-4",
    assignedToUserId: "user-4",
    createdAt: "2026-06-05T16:00:00.000Z",
  },
  {
    id: "activity-4",
    dealId: "DEAL-2026-006",
    type: "call",
    occurredAt: "2026-03-25",
    contactId: "cont-9",
    summary: "Initial technical presentation follow-up.",
    outcome: "No commitment; re-engage in Q2.",
    loggedByUserId: "user-3",
    createdAt: "2026-03-25T10:15:00.000Z",
  },
  {
    id: "activity-5",
    dealId: "DEAL-2026-007",
    type: "email",
    occurredAt: "2026-06-08",
    contactId: "cont-2",
    summary: "Shared preliminary specs for 1.5T variant.",
    loggedByUserId: "user-admin",
    createdAt: "2026-06-08T09:45:00.000Z",
  },
  {
    id: "activity-6",
    dealId: "DEAL-2026-005",
    type: "visit",
    occurredAt: "2026-06-12",
    contactId: "cont-7",
    summary: "Plant visit for sample evaluation follow-up.",
    outcome: "Review sample results on-site with QA team.",
    loggedByUserId: "user-admin",
    assignedToUserId: "user-admin",
    createdAt: "2026-06-01T09:00:00.000Z",
  },
];

export const reminders: CrmReminder[] = [
  {
    id: "reminder-1",
    userId: "user-2",
    kind: "task_assigned",
    title: "Present revised pricing with volume discount tiers",
    message: "Rajesh Kumar assigned you a task",
    dueDate: "2026-06-14",
    dealId: "DEAL-2026-001",
    taskId: "task-1",
    createdAt: "2026-05-28T10:00:00.000Z",
  },
];

export function getCustomerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getContactById(id: string): Contact | undefined {
  return contacts.find((c) => c.id === id);
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getDealById(id: string): Deal | undefined {
  return deals.find((d) => d.id === id);
}

export function getContactsByCustomerId(customerId: string): Contact[] {
  return contacts.filter((c) => c.customerId === customerId);
}

